### PR TITLE
Now it works great

### PR DESCRIPTION
**Pull request by m4xc4v413r4**

### CODE REVIEW

**Comment by Kruithne** [comment]
GitHub is not the place for attempts at humor.

**Comment by AcidWeb** [comment]
You would think that after 15 years of wow people would've learned that a series of events that starts with "Blizzard removed something, I'll just add it back" never results in a favorable outcome.

**Comment by Kruithne** [comment]
The add-on is not using the API calls that were disabled/protected. It's just inviting people into a group using the old `InviteUnit` function that's been part of the API since the beginning. If they have a problem with the add-on specifically, they can add it to the blacklisted add-ons list and be done with it. 

This is not the place for discussion. Please insert your non-constructive comments and opinions on the WoW forums so I can ignore them. Constructive feedback, bug reports or legitimate PRs are all that are warranted here.

**Comment by AcidWeb** [comment]
Relax they will be blocked pretty soon. We both know they just missed this way during blocking LFG automation mechanism.

**Pull request closed without merging**
